apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagestore-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagestore
  template:
    metadata:
      labels:
        app: imagestore
    spec:
      containers:
        - name: imagestore
          image: ezeedge/imagestore-app:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: imagestore-srv
spec:
  selector:
    app: imagestore
  ports:
    - name: imagestore
      protocol: TCP
      port: 80
      targetPort: 80