apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'auth'
        static_configs:
          - targets: ['auth-srv:3000']
      - job_name: 'tasks'
        static_configs:
          - targets: ['tasks-srv:3000']
